[application]
name = "phigros-ability"
default_platform = "web"
out_dir = "docs"
base_path = "phigros-ability"
asset_dir = "public"

[web.app]
title = "Phigros Ability"

[web.watcher]
reload_html = true
watch_path = ["src", "public"]

[web.resource]
style = ["tailwind.css"]
script = []

[web.resource.dev]
script = []
